### ISSUE TITLE
Unable to perform mvn fabric8:deploy -Pistio-openshift

### ISSUE THREAD

**Issue by geoand** [snowdrop/spring-boot-booster-parent#5]
While using version `1.5.10.Beta2` of the parent in [this](https://github.com/snowdrop/spring-boot-quickstart-istio) project, I encountered

`Execution default of goal io.fabric8:fabric8-maven-plugin:3.5.30:build failed: A required class was missing while executing io.fabric8:fabric8-maven-plugin:3.5.30:build: io/fabric8/kubernetes/api/model/SecurityContextConstraints`

I was finally able to get around the problem by dropping the parent from the project and going with bom instead (see [this](https://github.com/snowdrop/spring-boot-quickstart-istio/commit/5e5f9523d4f50a4328f6d7ac605f5d1e3020f6ad) commit)

**Comment by metacosm** [comment]
Looking at dependencies, the only difference is the inclusion of `io.openshift:openshift-test-utils` that comes from the OpenShift `booster-parent`. Since we moved all the tests to Arquillian Cube, we don't have a reason to include that dependency anymore but it seems (based on discussion with Clément) that it might not be the case for all runtimes. Trying options to mitigate the issue.

**Comment by metacosm** [comment]
Looks like the issue is the FMP version (3.5.0) defined in OpenShift's `booster-parent` (and which is inherited by the `spring-boot-booster-parent`) while the version without the parent is using FMP version 3.5.33. Mitigation is to release a new version overriding the OpenShift's parent version until such a time that a new version of that parent is released.

**Comment by geoand** [comment]
Very interesting! Thank you for getting to the bottom of it!

**Comment by metacosm** [comment]
Created a PR: https://github.com/openshiftio/booster-parent/pull/19

**Comment by metacosm** [comment]
Actually, looks like I cannot override the FMP version in our booster-parent… :(

**Comment by geoand** [comment]
Why does overriding the property not work?

**Comment by metacosm** [comment]
Nevermind, found a way! 💪

**Comment by metacosm** [comment]
That's what I ended up doing. I tried some other way first which didn't work. Maven sometimes work in mysterious ways.
